//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaQQ.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaQQ.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AvaQQ 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adapter is null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdapterIsNull {
            get {
                return ResourceManager.GetString("ExceptionAdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circular reference detected while loading plugin. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCircularReferenceDetected {
            get {
                return ResourceManager.GetString("ExceptionCircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to cast event bus with name &apos;{0}&apos; and category &apos;{1}&apos; to {2} from original type {3}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionEventBusCast {
            get {
                return ResourceManager.GetString("ExceptionEventBusCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event bus with name &apos;{0}&apos; and category &apos;{1}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionEventBusNotFound {
            get {
                return ResourceManager.GetString("ExceptionEventBusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not initialized. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotInitialized {
            get {
                return ResourceManager.GetString("ExceptionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation is only supported in design mode. 的本地化字符串。
        /// </summary>
        internal static string ExceptionOnlySupportedInDesignMode {
            get {
                return ResourceManager.GetString("ExceptionOnlySupportedInDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open ConnectWindow, because adapter is already set. 的本地化字符串。
        /// </summary>
        internal static string ExceptionOpenConnectWindow_AdapterAlreadySet {
            get {
                return ResourceManager.GetString("ExceptionOpenConnectWindow_AdapterAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open MainWindow, because adapter is null. 的本地化字符串。
        /// </summary>
        internal static string ExceptionOpenMainWindow_AdapterIsNull {
            get {
                return ResourceManager.GetString("ExceptionOpenMainWindow_AdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin dependency with id &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPluginDependencyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPluginDependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string MenuTextExit {
            get {
                return ResourceManager.GetString("MenuTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string TextConnect {
            get {
                return ResourceManager.GetString("TextConnect", resourceCulture);
            }
        }
    }
}
