//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaQQ.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaQQ.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error while preloading plugins. 的本地化字符串。
        /// </summary>
        internal static string ErrorErrorWhilePreloadingPlugins {
            get {
                return ResourceManager.GetString("ErrorErrorWhilePreloadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to discover plugin in &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorFailedToDiscoverPlugin {
            get {
                return ResourceManager.GetString("ErrorFailedToDiscoverPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load plugin assembly &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorFailedToLoadPluginAssembly {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadPluginAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load searching directory &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorFailedToLoadSearchingDirectory {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadSearchingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adapter was not set. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAdapterNotSet {
            get {
                return ResourceManager.GetString("ExceptionAdapterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The diameter of the avatar must be an even number. 的本地化字符串。
        /// </summary>
        internal static string ExceptionAvatarDiameterMustEven {
            get {
                return ResourceManager.GetString("ExceptionAvatarDiameterMustEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circular reference detected while loading plugin. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCircularReferenceDetected {
            get {
                return ResourceManager.GetString("ExceptionCircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectWindow was already opened. 的本地化字符串。
        /// </summary>
        internal static string ExceptionConnectWindowAlreadyOpened {
            get {
                return ResourceManager.GetString("ExceptionConnectWindowAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectWindow was not opened. 的本地化字符串。
        /// </summary>
        internal static string ExceptionConnectWindowNotOpened {
            get {
                return ResourceManager.GetString("ExceptionConnectWindowNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load configuration: &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        internal static string ExceptionFailedToLoadConfiguration {
            get {
                return ResourceManager.GetString("ExceptionFailedToLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainPanelWindow was already opened. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMainPanelWindowAlreadyOpened {
            get {
                return ResourceManager.GetString("ExceptionMainPanelWindowAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MainPanelWindow was not opened. 的本地化字符串。
        /// </summary>
        internal static string ExceptionMainPanelWindowNotOpened {
            get {
                return ResourceManager.GetString("ExceptionMainPanelWindowNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin dependency with id &quot;{0}&quot; not found. 的本地化字符串。
        /// </summary>
        internal static string ExceptionPluginDependencyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPluginDependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string TextConnect {
            get {
                return ResourceManager.GetString("TextConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect. 的本地化字符串。
        /// </summary>
        internal static string TextConnectFailed {
            get {
                return ResourceManager.GetString("TextConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friend 的本地化字符串。
        /// </summary>
        internal static string TextFriend {
            get {
                return ResourceManager.GetString("TextFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string TextGroup {
            get {
                return ResourceManager.GetString("TextGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Access Token... 的本地化字符串。
        /// </summary>
        internal static string TextInputAccessToken {
            get {
                return ResourceManager.GetString("TextInputAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input URL... 的本地化字符串。
        /// </summary>
        internal static string TextInputUrl {
            get {
                return ResourceManager.GetString("TextInputUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs 的本地化字符串。
        /// </summary>
        internal static string TextLogs {
            get {
                return ResourceManager.GetString("TextLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Onebot 11 - Forward Web Socket Adapter 的本地化字符串。
        /// </summary>
        internal static string TextOnebot11ForwardWebSocketAdapter {
            get {
                return ResourceManager.GetString("TextOnebot11ForwardWebSocketAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        internal static string TextRecent {
            get {
                return ResourceManager.GetString("TextRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an adapter 的本地化字符串。
        /// </summary>
        internal static string TextSelectAdapter {
            get {
                return ResourceManager.GetString("TextSelectAdapter", resourceCulture);
            }
        }
    }
}
